name: Run_tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Run_tests
        shell: bash
        run: |
          pytest -v
