name: Run_tests

on:
  push:
    branches: [ main ]
  pull_request: [ main ]

jobs:
  test:
    name: Run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Install python3
        shell: bash
        run: sudo apt install python3
      
      - name: Install pip
        shell: bash
        run: sudo apt install python3-pip
             
      - name: Install pytest
        shell: bash
        run: pip3 install pytest

      - name: Run_tests
        shell: bash
        run: pytest -v